baseURL = "https://www.standalonedynamics.co.za/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Standalone Dynamics"
theme = "hugo-coder"

contentDir = "content"
layoutDir = "layouts"
publishDir = "public"

[params]
author = "Menzi Mthembu"
avatarurl = "headshot.jpg"
dateformat = "Jan 2, 2006"
info = "Software Engineer"
colorScheme = "auto"
license = '<a href="http://creativecommons.org/licenses/by/3.0/">CC BY-SA-4.0</a>'



[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 2
url = "https://github.com/StandaloneDynamics"


[[params.social]]
name = "Twitter"
icon = "fa-brands fa-twitter fa-2x"
weight = 1
url = "https://x.com/StandaloneDyn"



[[menu.main]]
 name="Blog"
 weight=1
 identifier="blog"
  url="/blog"
[[menu.main]]
  name="About"
  identifier="about"
  weight=4
  url="/about"
[[menu.main]]
  name="Projects"
  identifier="projects"
  weight=2
  url="/projects"
[[menu.main]]
  name="Mini Guides"
  identifier="guides"
  weight=3
  url="/guides"


