baseURL = "https://www.standalonedynamics.co.za/"
languageCode = "en-us"
title = "Standalone Dynamics"
theme = "hugo-coder"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Menzi Mthembu"

[params]
author = "Menzi Mthembu"
intro = "Software Developer"
avatarurl = "headshot.png"
dateformat = "Jan 2, 2006"
info = "Software Developer"
colorScheme = "dark"



[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/StandaloneDynamics"


[params.meta]
description = "Standalone Dynamics"
keywords = "developer,software,python,django,rust,web,gtk"

[params.extra]
copyright = "© 2023. Menzi Mthembu. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
toc = true


[markup]
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 1


[[menu.main]]
    name="Blog"
    weight=200
    identifier="blog"
    url="/blog"
[[menu.main]]
    name="About"
    identifier="about"
    weight=100
    url="/about"
[[menu.main]]
    name="Projects"
    identifier="projects"
    weight=300
    url="/projects"
[[menu.main]]
    name="Mini Guides"
    identifier="guides"
    weight=400
    url="/guides"


